name: File check
run-name: File Check Run-name
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      WHITE_LIST: "piecehealth,herryz"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Assume PRs are less than 50 commits
          fetch-depth: 50
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: config/locales/generated/*.yml
      - name: Run step if any file(s) in the docs folder change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "List all the translation files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"

          if echo "$WHITE_LIST" | grep -qw "${{ github.actor }}"; then
            echo "User ${{ github.actor }} is allowed to make changes."
          else
            echo "Error: User ${{ github.actor }} is not authorized to make changes."
            exit 1
          fi
